# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20161016_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='parent_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu_item'),
        ),
    ]
