# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20161016_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='id_path',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
